config/routes.rb
MonstersInc::Application.routes.draw do
  get "static_pages/home"
  get "static_pages/help"
  resources :monsters

  root  'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/signup',  to: 'monsters#new',            via: 'get'

end

app/models/monster.rb
class Monster < ActiveRecord::Base
	validates(:name, presence: true)
	has_attached_file :avatar, 
			:styles => { :medium => "300x300>", :thumb => "100x100>" }, 
			:path => ":rails_root/uploads/:class/:id/:basename.:extension",
			:url => "/avatar/:id/download"
  	validates_attachment_content_type :avatar, :content_type => 
	['image/jpg','image/jpeg','image/pjpeg','image/png','image/x-png']
	has_secure_password
end

app/controllers/monsters_controller.rb
class MonstersController < ApplicationController
  before_action :set_monster, only: [:show, :edit, :update, :destroy]

  # GET /monsters
  # GET /monsters.json
  def index
    @monsters = Monster.paginate(page: params[:page])
  end

  # GET /monsters/1
  # GET /monsters/1.json
  def show
  end

  # GET /monsters/new
  def new
    @monster = Monster.new
  end

  # GET /monsters/1/edit
  def edit
  end

  # POST /monsters
  # POST /monsters.json
  def create
    @monster = Monster.new(monster_params)

    respond_to do |format|
      if @monster.save
        format.html { redirect_to @monster, notice: 'Monster was successfully created.' }
        format.json { render action: 'show', status: :created, location: @monster }
      else
        format.html { render action: 'new' }
        format.json { render json: @monster.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /monsters/1
  # PATCH/PUT /monsters/1.json
  def update
    respond_to do |format|
      if @monster.update(monster_params)
        format.html { redirect_to @monster, notice: 'Monster was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @monster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /monsters/1
  # DELETE /monsters/1.json
  def destroy
    @monster.destroy
    respond_to do |format|
      format.html { redirect_to monsters_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_monster
      @monster = Monster.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def monster_params
      params.require(:monster).permit(:name, :email, :password,
                                   :password_confirmation, :avatar)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/helpers/monsters_helper.rb
module MonstersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Monsters Inc. | <%= yield(:title) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "Monsters Inc.", root_path, id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home", root_path %></li>
              <li><%= link_to "Help", help_path %></li>
              <li><%= link_to "Monsters", monsters_path %></li>
            </ul>
          </nav>
        </div>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/monsters/_form.html.erb
<%= form_for @monster, :html => { :multipart => true } do |f| %>
  <% if @monster.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@monster.errors.count, "error") %> prohibited this monster from being saved:</h2>

      <ul>
      <% @monster.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="span6 offset3 field">
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :avatar %>
      <%= f.file_field :avatar %>

      <%= f.label :password %>
      <%= f.password_field :password%>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>

      <br><br>

      <%= f.submit "Create account", class: "btn btn-large btn-primary" %>
    </div>
  </div>
<% end %>

app/views/monsters/edit.html.erb
<h1>Editing monster</h1>

<%= render 'form' %>

<%= link_to 'Show', @monster %> |
<%= link_to 'Back', monsters_path %>

app/views/monsters/index.html.erb
<% provide(:title, 'All monsters') %>
<h1>All monsters</h1>

<%= will_paginate %>

<ul class="monsters">
  <% @monsters.each do |monster| %>
    <li>
    	<%= image_tag monster.avatar.url %>
    	<h5><%= monster.name%></h5>
    </li>
  <% end %>

</ul>

<%= will_paginate %>

app/views/monsters/new.html.erb
<h1>Create your Monster</h1>

<%= render 'form' %>

<%= link_to 'Back', monsters_path %>

app/views/monsters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @monster.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @monster.email %>
</p>

<%= link_to 'Edit', edit_monster_path(@monster) %> |
<%= link_to 'Back', monsters_path %>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="center hero-unit">
  <h1>Welcome to Monsters Inc.</h1>

  <%= link_to "Create your Monster", signup_path, class: "btn btn-large btn-primary" %>
</div>